[build]
  command = "python3 deploy.py"
  publish = "site"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/modules/*/frames/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
