"""Leaf-only Hosted Agent Bus marker vocabulary.

This module intentionally imports nothing from Agent Cycle, Agent Tool, lease,
transport, or authority layers. It exists so record scanners and producers can
share marker definitions without creating an import cycle or a second semantic
contract surface.
"""

AGENT_CYCLE_REQUEST_V02 = "MOBILIPRESENTER_AGENT_CYCLE_REQUEST_V0_2"

AGENT_TOOL_REQUEST_V01 = "MOBILIPRESENTER_AGENT_TOOL_REQUEST_V0_1"
AGENT_TOOL_REQUEST_V02 = "MOBILIPRESENTER_AGENT_TOOL_REQUEST_V0_2"
AGENT_TOOL_RESULT_V01 = "MOBILIPRESENTER_AGENT_TOOL_RESULT_V0_1"
AGENT_TOOL_DISPATCH_V01 = "MOBILIPRESENTER_AGENT_TOOL_DISPATCH_V0_1"

REMOTE_CANONICAL_REQUEST_V01 = "MOBILIPRESENTER_REMOTE_CANONICAL_REQUEST_V0_1"
REMOTE_CANONICAL_RESULT_V01 = "MOBILIPRESENTER_REMOTE_CANONICAL_RESULT_V0_1"

AGENT_WRITE_LEASE_REQUEST_V01 = "MOBILIPRESENTER_AGENT_WRITE_LEASE_REQUEST_V0_1"
AGENT_WRITE_LEASE_REQUEST_V02 = "MOBILIPRESENTER_AGENT_WRITE_LEASE_REQUEST_V0_2"
AGENT_WRITE_LEASE_DISPATCH_V01 = "MOBILIPRESENTER_AGENT_WRITE_LEASE_DISPATCH_V0_1"
AGENT_WRITE_LEASE_RESULT_V01 = "MOBILIPRESENTER_AGENT_WRITE_LEASE_RESULT_V0_1"
AGENT_WRITE_LEASE_ATTEMPT_V01 = "MOBILIPRESENTER_AGENT_WRITE_LEASE_ATTEMPT_V0_1"
